export const CREATE_PRISONER = "CREATE_PRISONER";
export const RETRIEVE_PRISONERS = "RETRIEVE_PRISONERS";
export const UPDATE_PRISONER = "UPDATE_PRISONER";
export const DELETE_PRISONER = "DELETE_PRISONER";
export const DELETE_ALL_PRISONERS = "DELETE_ALL_PRISONERS";

export const CREATE_PRISON = "CREATE_PRISON";
export const RETRIEVE_PRISONS = "RETRIEVE_PRISONS";
export const UPDATE_PRISON = "UPDATE_PRISON";
export const DELETE_PRISON = "DELETE_PRISON";
export const DELETE_ALL_PRISONS = "DELETE_ALL_PRISONS";

export const CREATE_USER = "CREATE_USER";
export const RETRIEVE_USERS = "RETRIEVE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_ALL_USERS = "DELETE_ALL_USERS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";

export const CREATE_RULE = "CREATE_RULE";
export const RETRIEVE_RULES = "RETRIEVE_RULES";
export const UPDATE_RULE = "UPDATE_RULE";
export const DELETE_RULE = "DELETE_RULE";

export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const RETREIVE_CONVERSATIONS = "RETRIEVE_CONVERSATIONS";
export const RETREIVE_MESSAGES = "RETREIVE_MESSAGES";
export const RETREIVE_UNSENT = "RETRIEVE_UNSENT";
export const UPDATE_CONVERSATION = "UPDATE_CONVERSATION";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE";
export const DELETE_CONVERSATION = "DELETE_CONVERSATION";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
